# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('large', models.ImageField(upload_to='photo/user/%Y/%m/%d')),
                ('med', django_resized.forms.ResizedImageField(upload_to='photo/user/%Y/%m/%d')),
                ('small', django_resized.forms.ResizedImageField(upload_to='photo/user/%Y/%m/%d')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User')),
            ],
        ),
    ]
