# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codehash',
            name='challenge',
            field=models.IntegerField(default=0),
        ),
    ]
