# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 03:58
from __future__ import unicode_literals

import common.utils.general
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('0', 'stored'), ('1', 'moved')], default='0', max_length=1)),
                ('update_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Reached Server'), ('1', 'Seen'), ('2', 'Downloaded'), ('3', 'Directlink'), ('4', 'Both')], default='0', max_length=1)),
                ('update_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectUnsignedView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_ip', models.CharField(max_length=16)),
                ('viewer_ua', models.CharField(max_length=512)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('path', models.FileField(max_length=512, upload_to=common.utils.general.Helper.getFilePath)),
                ('size', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=255, null=True)),
                ('sent_ts', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User')),
                ('recievers', models.ManyToManyField(related_name='Receiver', through='file.Delivery', to='common.User')),
            ],
        ),
        migrations.AddField(
            model_name='directunsignedview',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User'),
        ),
        migrations.AddField(
            model_name='blinddelivery',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File'),
        ),
    ]
