# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=255)),
                ('challenge', models.IntegerField(default=0)),
                ('responseagent', models.CharField(default=None, max_length=512, null=True)),
                ('requestip', models.CharField(default=None, max_length=16, null=True)),
                ('requestagent', models.CharField(default=None, max_length=512, null=True)),
                ('resolve_status', models.BooleanField(default=False)),
                ('mitigate', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=16, unique=True)),
                ('attempt', models.IntegerField(default=1)),
                ('uastring', models.CharField(default=None, max_length=512, null=True)),
                ('ipaddress', models.CharField(default=None, max_length=16, null=True)),
                ('ts', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
