application: hello-django-app-engine
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: default

handlers:
- url: .*
  script: myproject.wsgi.application

libraries:
- name: django
  version: 1.5
