# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nativecontact',
            unique_together=set([('contact', 'contact_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='unregisteredcontact',
            unique_together=set([('contact', 'contact_phone')]),
        ),
    ]
