# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170421_0848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nativecontact',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='unregisteredcontact',
            unique_together=set([]),
        ),
    ]
